"""add algorithm inventory table

Revision ID: 0544401d28c2
Revises: 9565469e72ec
Create Date: 2026-07-28 15:29:04.308709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0544401d28c2'
down_revision = '9565469e72ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('algorithm_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_name', sa.String(length=100), nullable=False),
    sa.Column('algorithm_name', sa.String(length=100), nullable=False),
    sa.Column('algorithm_type', sa.String(length=50), nullable=False),
    sa.Column('key_size', sa.String(length=50), nullable=True),
    sa.Column('quantum_risk', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('migration_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('algorithm_assets')
    # ### end Alembic commands ###
