"""add certificate crypto fields

Revision ID: 77622ebd692a
Revises: 48e8b1aab587
Create Date: 2026-07-28 22:17:54.624137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77622ebd692a'
down_revision = '48e8b1aab587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('algorithm', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('algorithm_category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('quantum_risk', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('migration_status', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('recommended_algorithm', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_column('recommended_algorithm')
        batch_op.drop_column('migration_status')
        batch_op.drop_column('quantum_risk')
        batch_op.drop_column('algorithm_category')
        batch_op.drop_column('algorithm')

    # ### end Alembic commands ###
