"""Rename resource column to module

Revision ID: 9565469e72ec
Revises: 983bb3e7374d
Create Date: 2026-07-27 12:41:44.526342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9565469e72ec'
down_revision = '983bb3e7374d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('module', sa.String(length=100), nullable=False))
        batch_op.drop_column('resource')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resource', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('module')

    # ### end Alembic commands ###
